# Generated by Django 6.0.2 on 2026-02-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0002_booking_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='000000', max_length=20, verbose_name='Broj mobitela'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ukupna cijena'),
        ),
    ]
