# Generated by Django 6.0.2 on 2026-03-17 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0003_booking_phone_number_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Unesite ispravan broj telefona. Dozvoljeni su samo brojevi i znak '+' na početku.", regex='^\\+?[0-9]{6,15}$')], verbose_name='Broj mobitela'),
        ),
    ]
