# Generated by Django 6.0.2 on 2026-05-12 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0004_alter_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_gosta', models.CharField(max_length=100, verbose_name='Ime i prezime')),
                ('tekst', models.TextField(verbose_name='Dojam o boravku')),
                ('ocjena', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocjena (1-5)')),
                ('odobreno', models.BooleanField(default=False, verbose_name='Odobreno za prikaz')),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recenzija',
                'verbose_name_plural': 'Recenzije',
                'ordering': ['-datum'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promokod',
            field=models.CharField(default=1, verbose_name='promo kod'),
            preserve_default=False,
        ),
    ]
